USE [master]
GO

/****** Object:  Database [publishing]    Script Date: 14.12.2025 18:37:02 ******/
DROP DATABASE [publishing]
GO

/****** Object:  Database [publishing]    Script Date: 14.12.2025 18:37:02 ******/
CREATE DATABASE [publishing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'publishing', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\publishing.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'publishing_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\publishing_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [publishing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [publishing] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [publishing] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [publishing] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [publishing] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [publishing] SET ARITHABORT OFF 
GO

ALTER DATABASE [publishing] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [publishing] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [publishing] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [publishing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [publishing] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [publishing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [publishing] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [publishing] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [publishing] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [publishing] SET  ENABLE_BROKER 
GO

ALTER DATABASE [publishing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [publishing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [publishing] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [publishing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [publishing] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [publishing] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [publishing] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [publishing] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [publishing] SET  MULTI_USER 
GO

ALTER DATABASE [publishing] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [publishing] SET DB_CHAINING OFF 
GO

ALTER DATABASE [publishing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [publishing] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [publishing] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [publishing] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [publishing] SET QUERY_STORE = ON
GO

ALTER DATABASE [publishing] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [publishing] SET  READ_WRITE 
GO

